### ISSUE TITLE
large docker container log

### ISSUE THREAD

**Issue by meonkeys** [dsteinkopf/elasticsearch-ingest-attachment#1]
I noticed the logs for my `dsteinkopf/elasticsearch-ingest-attachment` container are quite large (over 1GB).

Is there some way to auto-rotate these?

Is this perhaps indicative of a problem? I've never bothered to inspect this log. Full text search in Nextcloud appears to be working fine.

Thanks, -Adam

**Comment by meonkeys** [comment]
I'm going to try setting `log-opts` → `max-size` in my Docker daemon config file (`/etc/docker/daemon.json`)
https://docs.docker.com/engine/reference/commandline/dockerd/#daemon-configuration-file

**Comment by dsteinkopf** [comment]
Thank you for using my container. But I fear I am not able to help you.
Could you please refer to the base package https://www.docker.elastic.co/r/elasticsearch/elasticsearch (see https://github.com/dsteinkopf/elasticsearch-ingest-attachment/blob/master/Dockerfile)?
